# Generated by Django 3.2.20 on 2023-10-01 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('phone_number', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('ward', models.CharField(choices=[('Ward1', 'Ward 1'), ('Ward2', 'Ward 2'), ('Ward3', 'Ward 3'), ('Other', 'Other')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Busaryapproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('phone_number', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('ward', models.CharField(choices=[('Ward1', 'Ward 1'), ('Ward2', 'Ward 2'), ('Ward3', 'Ward 3'), ('Other', 'Other')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
