# Generated by Django 3.2.20 on 2023-10-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busary', '0007_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='busary',
            name='admission_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busary',
            name='education_level',
            field=models.CharField(choices=[('High School', 'High School'), ('Collage', 'Collage'), ('University', 'University')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busary',
            name='parent_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busary',
            name='school_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busaryapproved',
            name='admission_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busaryapproved',
            name='education_level',
            field=models.CharField(choices=[('High School', 'High School'), ('Collage', 'Collage'), ('University', 'University')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busaryapproved',
            name='parent_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busaryapproved',
            name='school_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
