# Generated by Django 4.2.6 on 2023-10-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busary', '0008_auto_20231001_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busary',
            name='ward',
            field=models.CharField(choices=[('Magutu', 'Magutu'), ('Konyu', 'Konyu'), ('Iria-ini', 'Iria-ini'), ('Ruguru', 'Ruguru'), ('Giathieko', 'Giathieko'), ('Gikondi', 'Gikondi'), ('Karatina Town', 'Karatina Town'), ('Kiamathaga', 'Kiamathaga')], max_length=50),
        ),
        migrations.AlterField(
            model_name='busaryapproved',
            name='ward',
            field=models.CharField(choices=[('Magutu', 'Magutu'), ('Konyu', 'Konyu'), ('Iria-ini', 'Iria-ini'), ('Ruguru', 'Ruguru'), ('Giathieko', 'Giathieko'), ('Gikondi', 'Gikondi'), ('Karatina Town', 'Karatina Town'), ('Kiamathaga', 'Kiamathaga')], max_length=50),
        ),
    ]
