# Generated by Django 3.2.20 on 2023-09-17 08:00

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(limit_value=10, message='Phone number must be at least 10 digits.'), django.core.validators.MaxLengthValidator(limit_value=10, message='Phone number can have at most 10 digits.'), django.core.validators.RegexValidator(message='Phone number must contain only digits.', regex='^[0-9]{10}$')])),
                ('project', models.CharField(choices=[('NG-CDF Projects', 'NG-CDF Projects'), ('Road Projects', 'Road Projects'), ('Uwezo Fund Program', 'Uwezo Fund Program'), ('TCDL Programs', 'TCDL Programs'), ('Diversity and Inclusion', 'Diversity and Inclusion'), ('Other', 'Other')], max_length=50)),
                ('ward', models.CharField(choices=[('Ward1', 'Ward 1'), ('Ward2', 'Ward 2'), ('Ward3', 'Ward 3'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(choices=[('Location1', 'Location 1'), ('Location2', 'Location 2'), ('Location3', 'Location 3'), ('Other', 'Other')], max_length=50)),
                ('sub_location', models.CharField(choices=[('SubLocation1', 'Sub-Location 1'), ('SubLocation2', 'Sub-Location 2'), ('SubLocation3', 'Sub-Location 3'), ('Other', 'Other')], max_length=50)),
            ],
        ),
    ]
