# Generated by Django 4.2.6 on 2023-10-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_location_alter_project_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectapproved',
            name='project_description',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
