# Generated by Django 3.2.20 on 2023-09-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busary_images', models.ImageField(upload_to='static/img/busary')),
                ('corousel_images', models.ImageField(upload_to='static/img/corousel')),
                ('events_images', models.ImageField(upload_to='static/img/events')),
                ('outlook_images', models.ImageField(upload_to='static/img/outlook')),
                ('projects_images', models.ImageField(upload_to='static/img/projects')),
                ('team_images', models.ImageField(upload_to='static/img/outlook')),
            ],
        ),
    ]
