# Generated by Django 3.2.20 on 2023-09-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20230926_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizer',
            name='events_images',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/events'),
        ),
        migrations.AddField(
            model_name='customizer',
            name='projects_images',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/projects'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='busary_images',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/busary'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='corousel_images',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/corousel'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='outlook_images',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/outlook'),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='team_images',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/outlook'),
        ),
    ]
