# Generated by Django 3.2.20 on 2023-09-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_customizer_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizer',
            name='image_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
