# Generated by Django 3.2.20 on 2023-09-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_customizer_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizer',
            name='image_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='image_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customizer',
            name='team_images',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/team'),
        ),
    ]
