# Generated by Django 3.2.20 on 2023-09-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20230927_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busary_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busary_images', models.ImageField(blank=True, null=True, upload_to='static/img/busary')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_images', models.ImageField(upload_to='static/img/events')),
                ('event_type', models.CharField(choices=[('Upcoming', 'upcoming'), ('Past', 'Past')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcoming_projects', models.ImageField(blank=True, null=True, upload_to='static/img/projects/upcoming')),
                ('past_projects', models.ImageField(blank=True, null=True, upload_to='static/img/projects/past')),
                ('ongoing_projects', models.ImageField(blank=True, null=True, upload_to='static/img/projects/ongoing')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=20)),
                ('image_name', models.CharField(max_length=20)),
                ('team_images', models.ImageField(upload_to='static/img/team')),
            ],
        ),
        migrations.RemoveField(
            model_name='customizer',
            name='busary_images',
        ),
        migrations.RemoveField(
            model_name='customizer',
            name='events_images',
        ),
        migrations.RemoveField(
            model_name='customizer',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='customizer',
            name='image_title',
        ),
        migrations.RemoveField(
            model_name='customizer',
            name='projects_images',
        ),
        migrations.RemoveField(
            model_name='customizer',
            name='team_images',
        ),
    ]
