# Generated by Django 3.2.20 on 2023-09-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20230927_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corousel_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corousel_images', models.ImageField(blank=True, null=True, upload_to='static/img/corousel')),
            ],
        ),
        migrations.CreateModel(
            name='Outlook_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlook_images', models.ImageField(blank=True, null=True, upload_to='static/img/outlook')),
            ],
        ),
        migrations.DeleteModel(
            name='Customizer',
        ),
    ]
