# Generated by Django 3.2.20 on 2023-09-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20230927_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_images',
            name='event_type',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Past', 'Past')], max_length=50),
        ),
    ]
