# Generated by Django 3.2.20 on 2023-09-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_event_images_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ongoing_Project_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ongoing_projects', models.ImageField(blank=True, null=True, upload_to='static/img/projects/ongoing')),
            ],
        ),
        migrations.CreateModel(
            name='Past_Project_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past_projects', models.ImageField(blank=True, null=True, upload_to='static/img/projects/past')),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming_Project_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcoming_projects', models.ImageField(blank=True, null=True, upload_to='static/img/projects/upcoming')),
            ],
        ),
        migrations.DeleteModel(
            name='Project_Images',
        ),
    ]
