# Generated by Django 3.2.20 on 2023-09-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20230927_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='corousel_images',
            name='corousel_type',
            field=models.CharField(choices=[('Busary', 'Busary'), ('Project', 'Project'), ('Oppotunity', 'Oppotunity'), ('Proffession', 'Proffession'), ('Appointment', 'Appointment'), ('Diaspora', 'Diaspora')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
