# Generated by Django 3.2.20 on 2023-09-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_corousel_images_corousel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corousel_images',
            name='corousel_type',
            field=models.CharField(choices=[('busary', 'busary'), ('project', 'project'), ('oppotunity', 'oppotunity'), ('proffessionals', 'proffessionals'), ('appointment', 'appointment'), ('diaspora', 'diaspora')], max_length=50),
        ),
    ]
