# Generated by Django 3.2.20 on 2023-09-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_alter_corousel_images_corousel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ongoing_project_images',
            old_name='ongoing_projects',
            new_name='Ongoing_Project',
        ),
        migrations.RenameField(
            model_name='past_project_images',
            old_name='past_projects',
            new_name='Past_Project',
        ),
        migrations.RenameField(
            model_name='upcoming_project_images',
            old_name='upcoming_projects',
            new_name='Upcoming_Project',
        ),
    ]
