# Generated by Django 4.2.6 on 2023-10-11 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_auto_20231002_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_images',
            name='event_agenda',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_images',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event_images',
            name='event_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_images',
            name='event_place',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
