# Generated by Django 4.2.6 on 2023-10-13 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_event_images_event_agenda_event_images_event_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busary_images',
            old_name='busary_images',
            new_name='Busary',
        ),
        migrations.RenameField(
            model_name='corousel_images',
            old_name='corousel_images',
            new_name='Corousel',
        ),
        migrations.RenameField(
            model_name='event_images',
            old_name='events_images',
            new_name='Event',
        ),
        migrations.RenameField(
            model_name='outlook_images',
            old_name='outlook_images',
            new_name='Outlook',
        ),
        migrations.RenameField(
            model_name='team_images',
            old_name='team_images',
            new_name='Team',
        ),
    ]
