# Generated by Django 4.2.6 on 2023-10-13 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_ongoing_project_images_project_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('project_type', models.CharField(max_length=20)),
                ('project_location', models.CharField(max_length=20)),
                ('project_date', models.DateField(default=django.utils.timezone.now)),
                ('project_image', models.ImageField(upload_to='static/img/projects/ongoing')),
                ('corousel_type', models.CharField(choices=[('Ongoing_Project', 'Ongoing_Project'), ('Past_Project', 'Past_Project'), ('Upcoming_Project', 'Upcoming_Project')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Ongoing_Project_Images',
        ),
        migrations.DeleteModel(
            name='Past_Project_Images',
        ),
        migrations.DeleteModel(
            name='Upcoming_Project_Images',
        ),
    ]
