# Generated by Django 4.2.6 on 2023-10-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_project_images_delete_ongoing_project_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_images',
            name='corousel_type',
        ),
        migrations.AlterField(
            model_name='project_images',
            name='project_type',
            field=models.CharField(choices=[('Ongoing_Project', 'Ongoing_Project'), ('Past_Project', 'Past_Project'), ('Upcoming_Project', 'Upcoming_Project')], max_length=50),
        ),
    ]
