# Generated by Django 4.2.6 on 2023-10-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_remove_project_images_corousel_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_images',
            name='project_image',
        ),
        migrations.AddField(
            model_name='project_images',
            name='Project',
            field=models.ImageField(default=1, upload_to='static/img/projects'),
            preserve_default=False,
        ),
    ]
