# Generated by Django 3.2.20 on 2023-09-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20230917_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='country_Code',
        ),
    ]
