# Generated by Django 3.2.20 on 2023-09-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_appointment_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='agenda',
            field=models.CharField(max_length=50),
        ),
    ]
