# Generated by Django 3.2.20 on 2023-09-25 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentapproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=8)),
                ('phone_number', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=2)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ward', models.CharField(choices=[('Ward1', 'Ward 1'), ('Ward2', 'Ward 2'), ('Ward3', 'Ward 3'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(choices=[('Location1', 'Location 1'), ('Location2', 'Location 2'), ('Location3', 'Location 3'), ('Other', 'Other')], max_length=50)),
                ('sub_location', models.CharField(choices=[('SubLocation1', 'Sub-Location 1'), ('SubLocation2', 'Sub-Location 2'), ('SubLocation3', 'Sub-Location 3'), ('Other', 'Other')], max_length=50)),
                ('agenda', models.CharField(max_length=50)),
                ('education_level', models.CharField(choices=[('High School', 'High School'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Other', 'Other')], max_length=50)),
            ],
        ),
    ]
