# Generated by Django 4.2.6 on 2023-10-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20230927_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.CharField(choices=[('Magutu', 'Magutu'), ('Konyu', 'Konyu'), ('Mugunda', 'Mugunda'), ('Ruguru', 'Ruguru'), ('Karatina', 'Karatina'), ('Kiawara', 'Kiawara'), ('Gatitu', 'Gatitu'), ('Gitugi', 'Gitugi'), ('Iriaini', 'Iriaini'), ('Muhito', 'Muhito'), ('Karima', 'Karima'), ('Rwathia', 'Rwathia'), ('Thunguma', 'Thunguma'), ('Muruguru', 'Muruguru'), ('Kagochi', 'Kagochi'), ('Kiriita', 'Kiriita'), ('Kiamathura', 'Kiamathura'), ('Gakawa', 'Gakawa'), ('Kiangoma', 'Kiangoma'), ('Ngangarithi', 'Ngangarithi'), ('Gakindu', 'Gakindu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ward',
            field=models.CharField(choices=[('Magutu', 'Magutu'), ('Konyu', 'Konyu'), ('Iria-ini', 'Iria-ini'), ('Ruguru', 'Ruguru'), ('Giathieko', 'Giathieko'), ('Gikondi', 'Gikondi'), ('Karatina Town', 'Karatina Town'), ('Kiamathaga', 'Kiamathaga')], max_length=50),
        ),
        migrations.AlterField(
            model_name='appointmentapproved',
            name='location',
            field=models.CharField(choices=[('Magutu', 'Magutu'), ('Konyu', 'Konyu'), ('Mugunda', 'Mugunda'), ('Ruguru', 'Ruguru'), ('Karatina', 'Karatina'), ('Kiawara', 'Kiawara'), ('Gatitu', 'Gatitu'), ('Gitugi', 'Gitugi'), ('Iriaini', 'Iriaini'), ('Muhito', 'Muhito'), ('Karima', 'Karima'), ('Rwathia', 'Rwathia'), ('Thunguma', 'Thunguma'), ('Muruguru', 'Muruguru'), ('Kagochi', 'Kagochi'), ('Kiriita', 'Kiriita'), ('Kiamathura', 'Kiamathura'), ('Gakawa', 'Gakawa'), ('Kiangoma', 'Kiangoma'), ('Ngangarithi', 'Ngangarithi'), ('Gakindu', 'Gakindu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='appointmentapproved',
            name='ward',
            field=models.CharField(choices=[('Magutu', 'Magutu'), ('Konyu', 'Konyu'), ('Iria-ini', 'Iria-ini'), ('Ruguru', 'Ruguru'), ('Giathieko', 'Giathieko'), ('Gikondi', 'Gikondi'), ('Karatina Town', 'Karatina Town'), ('Kiamathaga', 'Kiamathaga')], max_length=50),
        ),
    ]
