# Generated by Django 3.2.20 on 2023-09-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proffessionals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proffession',
            name='country_Code',
        ),
        migrations.AddField(
            model_name='proffession',
            name='education_level',
            field=models.CharField(choices=[('High School', 'High School'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('Other', 'Other')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proffession',
            name='age',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='proffession',
            name='id_number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='proffession',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
